springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true
    csrf:
      enabled: true
    displayRequestDuration: true
    operationsSorter: alpha
    tagsSorter: alpha
spring:
  application:
    name: "Muziek API"
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017/muziek
      database: muziek