springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true
   
spring:
  application:
    name: "Muziek API"
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017/muziek
      database: muziek